language: node_js
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greetings_tests

node_js:
  - "v9.11.2"

services:
  - postgresql

before_script:
  - psql -c 'create database  greetings_tests;' -U postgres
  - psql -U postgres -d greetings_tests -a -f database.sql
 
addons:
  apt:
    packages:
    - postgresql-server-dev-9.2